{{ if .Values.nfsServer }}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: "{{ .Release.Namespace }}-pv"
  labels:
    name: "{{ .Release.Namespace }}-pv"
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  mountOptions:
    - nfsvers=4.1
  nfs:
    path: /
    server: {{ .Values.nfsServer }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: marklogic-shared-data
  namespace: {{ .Release.Namespace }}
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: ""
  volumeMode: Filesystem
  volumeName: "{{ .Release.Namespace }}-pv"
selector:
    matchLabels:
      name: "{{ .Release.Namespace }}-pv"
{{ end }}